[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'

[[plugins]]
repo = 'leafgarland/typescript-vim'

[[plugins]]
repo = 'lambdalisue/vim-fern'

[[plugins]]
repo = 'wsdjeg/vim-fetch'

[[plugins]]
repo = 'pangloss/vim-javascript'

[[plugins]]
repo = 'MaxMEllon/vim-jsx-pretty'

[[plugins]]
repo = 'mattn/vim-treesitter'
