# =============================
# Color
# =============================

# ------------------------------
# Blue
# ------------------------------
# https://huemint.com/brand-intersection/#palette=222123-121dea-a09ab0-dde5f0
# #222123
# #121dea
# #a09ab0
# #dde5f0

# ------------------------------
# Yellow
# ------------------------------
# https://huemint.com/brand-intersection/#palette=f5f1e6-1c2121-5d5c57-f4cc20
# #f5f1e6
# #1c2121
# #5d5c57
# #f4cc20

# ------------------------------
# Purple
# ------------------------------
# https://huemint.com/brand-intersection/#palette=251f1d-c8bdcf-6f72ea-302967
# #251f1d
# #c8bdcf
# #6f72ea
# #302967

format = """
[░▒▓](#f5f1e6)\
$hostname\
[ 󰾞🐙 ](bg:#f5f1e6)\
[](bg:#f4cc20 fg:#f5f1e6)\
$directory\
[](fg:#f4cc20 bg:#1c2121)\
$git_branch\
$git_status\
[](fg:#1c2121)\
$nodejs\
$rust\
$golang\
$php\
$cmd_duration\
$fill\
$git_metrics\
\n$character
"""
# [](fg:#394260 bg:#212736)

[fill]
symbol = ' '

[directory]
style = "fg:#1c2121 bg:#f4cc20"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#f5f1e6 bg:#1c2121)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($conflicted$stashed$deleted $renamed$modified$staged$untracked)](fg:#f5f1e6 bg:#1c2121)]($style)'

[git_metrics]
added_style = 'fg:#9ece6a bg:#1a1b26'
deleted_style = 'fg:#9ece6a bg:#1a1b26'
format = """[](fg:#1c2121)\
					[[+$added/-$deleted](fg:#f5f1e6 bg:#1c2121)\
					[](fg:#1c2121)\
					]($deleted_style)
					"""
disabled = false
# [](fg:#394260 bg:#212736)

[cmd_duration]
min_time = 1
style = 'fg:#f5f1e6'
format = "[ $duration]($style)"

[nodejs]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[rust]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[golang]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[php]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[hostname]
ssh_only = true
format = '[$hostname](bg:#f5f1e6 fg:#1c2121)'
disabled = false
aliases = { "popyson-mbp" = "home" }

# [time]
# disabled = true
# time_format = "%R" # Hour:Minute Format
# style = "bg:#1d2230"
# format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'
